### ISSUE TITLE
Enable to run analysis in multiple batches

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#109]
I think that for complicated analysis, where one has to run over many large samples, it may be not possible to run it in one-go (especially on small clusters). So we need to be able so split the production into multiple steps, each running over a subset of samples (I am thinking of 3 runs: over V+jets, Top+TT, Other MC + DATA).
That means that: 
* Output `.coffea` file should not be overwritten by subsequent runs that use existing `output_directory`. Instead it could be appended with _N subscript, or something like that.
* Plotting script must be able to take a list of `.coffea` files, concatenate them and only then proceed to plotting.

Btw, this is the way it is implemented in [BTVNanoCommissioning](https://github.com/cms-btv-pog/BTVNanoCommissioning/tree/master) framework.

**Comment by valsdav** [comment]
Hi @andreypz . At the moment the default is already to run separately for each dataset. There is an option `--full` to run all together. 
https://github.com/PocketCoffea/PocketCoffea/blob/main/scripts/runner.py#L378

Separate output file are generated for separate datasets. 

I'm not sure the plotting scripts are then using the list of files separately. Need to check 

Of course the interface can be improved to customize the grouping of the dataset to run. A too large splitting can introduce inefficiencies in the running (all workers waiting for a single late chunk instead of moving to the next dataset).

**Comment by andreypz** [comment]
Hmm. Ok, I see. This is implemented for dask/lxplus. But I am running parsl/condor runner at RWTH. With this setup it is running full-mode always. Maybe I can implement the split per sample, same as it's done for dask.
Then, the question of plotting still stands - I don't see how it would concatenate the files at the moment.

**Comment by valsdav** [comment]
yeah, the refactoring of `runner.py` is becoming urgent. @mmarchegiani already had some changes in the making. We will try to converge on them and propose a solution to support better multiple sites.

**Comment by andreypz** [comment]
This has been fixed with new `runner.py`
