### ISSUE TITLE
Possible key missing in plot_utils

### ISSUE THREAD

**Issue by piosifid** [PocketCoffea/PocketCoffea#203]
<img width="1022" alt="image" src="https://github.com/PocketCoffea/PocketCoffea/assets/143401995/31adb39b-9192-4ccb-85f6-3a77445210bf">
I get this error but when i locally add the key for the eras its is fine

**Comment by piosifid** [comment]
To further explain, when in my workfolw.py i add the function [define_custom_axes_extra] which is supported by pocketcoffea, the plotting script seems not to support it

**Comment by mmarchegiani** [comment]
Hi @piosifid, coming back to this issue in the plotting code, taking into account that the plotting code changed in the meanwhile, but I think this issue is unsolved yet.
At line [L369](https://github.com/PocketCoffea/PocketCoffea/blob/2a1efc7950cfa8262907335b15a430ef535b79e5/pocket_coffea/utils/plot_utils.py#L369) of `plot_utils.py` we are assigning attributes to the `Shape` objects in the case in which the histogram contains also data. Since when we add a custom axis `era` it is not contained in the dictionary `{'year': 'years', 'cat': 'categories'}`, a `KeyError` will be raised, which means that at the moment we are considering only `year` and `cat` as possible categorical axes in the input histograms.
In order to fix this, we should consider the possibility that additional categorical axes can be defined by the user and should be loaded as attributes accordingly.
I will have a look into this issue to see how it can be solved.

Otherwise, have you found a custom fix for the issue in the meantime?

**Comment by mmarchegiani** [comment]
Solved in #227.
Now the user can specify additional categorical axes needed for plotting, for data and MC independently.
