### ISSUE TITLE
Default histograms for jets are year-dependent

### ISSUE THREAD

**Issue by valsdav** [PocketCoffea/PocketCoffea#235]
Tests are failing because some default branch for jet histograms is available only in Run3 (new taggers): 

https://github.com/PocketCoffea/PocketCoffea/blob/f25c1610e09137783201f4844f293929de4927e8/pocket_coffea/parameters/histograms.py#L527

https://gitlab.cern.ch/cms-analysis/general/PocketCoffea/-/jobs/43850735

FYI @andreypz:  I think we should remove them from the histogram jet branches and create 2 helper functions to get default histograms for Run2 and Run3 taggers. What do you think?

**Comment by andreypz** [comment]
I see, I have not thought of that. I agree, please remove them for now.
As for the helping functions - that sounds reasonable, but I'm not sure how to implement that. And I will not be able to do it this week for sure. If you have a concrete idea, please implement it. otherwise I will take a look next week.

**Comment by valsdav** [comment]
It should be fixed by https://github.com/PocketCoffea/PocketCoffea/commit/66da43c2827502a3d16c942d1b70103cc282c78d . It can be further improved :)
